import matplotlib.pyplot as plt
import numpy as np
from math import cos, sqrt
import math

# Function to read data from file
def read_data(file_path):
    data = np.loadtxt(file_path)
    return data[:, 0], data[:, 1], data[:, 2] , data[:,3]

# Path to the output file generated by the Fortran program
file_path = 'result_Euler.out'

# Read data from the file
x, v, t ,E = read_data(file_path)

# Analytical solution
analytical_solution = 0.5*20*(x**2)+0.5*(v**2)

# Plotting the results
plt.figure(figsize=(8, 6))
plt.plot(t, E, label='Euler Method')
plt.plot(t, analytical_solution, label='Analytical Solution', linestyle='dashed')
plt.title('Euler Method Results vs Analytical Solution')
plt.xlabel('Time (t)')
plt.ylabel('Energy(E), delta_t=0.1')
plt.legend()
plt.grid(True)
plt.show()

